# Generated by Django 2.1.5 on 2019-01-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20160502_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='activity',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
