# Generated by Django 2.1.5 on 2019-01-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(default='token', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=60)),
                ('place', models.CharField(default='', max_length=200)),
                ('qq', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(to='userpage.Person'),
        ),
    ]
